apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: "kube-registry-proxy-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: kube-registry
    kubernetes.io/cluster-service: "true"
    version: v0.4
    app: {{ include "docker-registry.name" . }}
    chart: {{ include "docker-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        k8s-app: "docker-registry-{{ .Release.Name }}"
        kubernetes.io/name: "kube-registry-proxy"
        kubernetes.io/cluster-service: "true"
        version: v0.4
    spec:
      containers:
      - name: kube-registry-proxy
        image: gcr.io/google_containers/kube-registry-proxy:0.4
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: REGISTRY_HOST
          value: "docker-registry-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local"
        - name: REGISTRY_PORT
          value: "5000"
        ports:
        - name: registry
          containerPort: 80
          hostPort: 5000
