version: "3.5"
services:
  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    networks:
      - hydronet
    environment:
      - "POSTGRES_DB=docker"
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"

  manager:
    image: hydrosphere/serving-manager:latest
    container_name: manager
    networks:
      - hydronet
    depends_on:
      - postgres
      - sidecar
    environment:
      - "ADVERTISED_MANAGER_HOST=manager"
      - "ADVERTISED_MANAGER_PORT=9091"
      - "DATABASE_HOST=postgres"
      - "LOCAL_MODEL_PATH=/models"
      - "SIDECAR_HOST=sidecar"
      - "NETWORK_NAME=automation_hydronet"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MODEL_DIRECTORY}:/models


  sidecar:
    image: hydrosphere/serving-sidecar:latest
    container_name: sidecar
    ports:
      - "8080:8080"
      - "8082:8082"
    networks:
      - extnet
      - hydronet
    environment:
      - "MANAGER_HOST=manager"
      - "MANAGER_PORT=9091"
      - "SERVICE_NAME=manager"
      - "SERVICE_ID=-20"

  managerui:
    image: hydrosphere/serving-manager-ui:latest
    container_name: managerui
    ports:
      - "8083:80"
    networks:
      - extnet
      - hydronet
    environment:
      - "MANAGER_HOST=sidecar:8080"

networks:
  hydronet:
    name: automation_hydronet
    internal: true

  extnet:
    driver: bridge