version: "2"
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "docker"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"

  hydro-serving-manager:
    image: hydrosphere/serving-manager:latest
    ports:
      - "8080:8080"
      - "8082:8082"
      - "9090:9090" # HTTP API
      - "9091:9091" # GRPC API
    depends_on:
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MODEL_DIRECTORY}:/models
    environment:
      ADVERTISED_MANAGER_HOST: "hydro-serving-manager"
      DATABASE_HOST: "postgres"
      LOCAL_MODEL_PATH: "/models"
      NETWORK_NAME: "hydroserving_default"
