version: "2"
services:
  zipkin:
    image: openzipkin/zipkin:1.28.1
    ports:
      - "9411:9411"

  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "docker"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"

  hydro-serving-manager:
    image: hydro-serving/manager:0.0.1
    ports:
      - "8080:8080"
      - "8082:8082"
      - "9090:9090"
    depends_on:
      - postgres
      - zipkin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MODEL_DIRECTORY}:/models
    environment:
      ADVERTISED_MANAGER_HOST: "hydro-serving-manager"
      DATABASE_HOST: "postgres"
      ZIPKIN_ENABLED: "true"
      ZIPKIN_HOST: "zipkin"
      DOCKER_NETWORK_NAME: "hydroserving_default"
