apiVersion: v1
kind: Service
metadata:
  name: "hydro-serving-manager-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "manager.name" . }}
    chart: {{ include "manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service_id: "id-20"
    hs_service_marker: "hs_service_marker"
    runtime_id: "id-20"
    service_name: "manager"
    deployment_type: "app"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http_port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc_port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: {{ include "manager.name" . }}
    release: {{ .Release.Name }}
