dependencies:
  - name: docker-registry
    repository: file://../docker-registry
    version: 0.1.0
    condition: global.dockerRegistry.enabled
  - name: postgres
    repository: file://../postgres
    version: 0.1.0
    condition: global.postgres.enabled
  - name: influx
    repository: file://../influx
    version: 0.1.0
    condition: global.influx.enabled
  - name: manager
    repository: file://../manager
    version: 0.1.0
  - name: ui
    repository: file://../ui
    version: 0.1.0
  - name: gateway
    repository: file://../gateway
    version: 0.1.0
