apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: autood-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "auto-od.name" . }}
      release: {{ .Release.Name }}