apiVersion: v1
entries:
  serving:
  - apiVersion: v1
    created: 2018-09-21T14:44:51Z
    description: A Helm chart for Kubernetes
    digest: 99dde70e22a7d350f2627beff5d577d8ab68333b7bc3ae14579d62fb8208c7f6
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving-helm/releases/download/0.1.7/serving-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v1
    created: 2018-10-07T15:35:24Z
    description: A Helm chart for Kubernetes
    digest: a6f4be33807c57f4829dafab0577c5de8bc6c0a0c2d63ee3b3cb63132fdf63ab
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving-helm/releases/download/0.1.8/serving-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v1
    created: 2018-10-07T15:40:38Z
    description: A Helm chart for Kubernetes
    digest: 0f8a969aac4517ee3e3212bd934ceb114c9efcae08620d44b26916ff0e5b5318
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving-helm/releases/download/0.1.9/serving-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v1
    created: 2018-10-07T16:03:05Z
    description: A Helm chart for Kubernetes
    digest: 315b175a9e2ee778b790ecf1071f237fbf7783c439625511ecded967a222706e
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving-helm/releases/download/0.1.10/serving-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v1
    created: 2018-10-07T16:38:41Z
    description: A Helm chart for Kubernetes
    digest: 0acb12565f1cb9f72e4428d4a6b234270c71ebe3c2c089f52cd0dd12e0944c5f
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving-helm/releases/download/0.1.11/serving-0.1.11.tgz
    version: 0.1.11
  - apiVersion: v1
    created: 2018-10-09T13:22:57Z
    description: A Helm chart for Kubernetes
    digest: d78d0a67cbed4ef6b0489878c577349848887b03112af4e204507fb67584c006
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving-helm/releases/download/0.1.12/serving-0.1.12.tgz
    version: 0.1.12
  - apiVersion: v1
    created: 2018-10-24T18:45:44Z
    description: A Helm chart for Kubernetes
    digest: db99766001029be29e819884570bac556031360b6ac73ef7cf133d968f4f13c1
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving-helm/releases/download/0.1.13/serving-0.1.13.tgz
    version: 0.1.13
  - apiVersion: v1
    created: 2018-10-24T18:58:16Z
    description: A Helm chart for Kubernetes
    digest: eb4e0dc6be5723e73072670f04fece98b0e143899df64a8937a4430005e40081
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving-helm/releases/download/0.1.14/serving-0.1.14.tgz
    version: 0.1.14
  - apiVersion: v1
    created: 2018-10-24T19:37:09Z
    description: A Helm chart for Kubernetes
    digest: b094fd9c4eac90a37ece124beadaf1b4f0ea6f424b78d41e797962cbcc8d47bb
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving-helm/releases/download/0.1.15/serving-0.1.15.tgz
    version: 0.1.15
  - apiVersion: v1
    created: 2019-03-27T18:31:28Z
    description: A Helm chart for Kubernetes
    digest: 2e71d697de1a4d24b25f8b48e389d88519578e022642d8932507ef5e3cae760e
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving-helm/releases/download/0.1.16/serving-0.1.16.tgz
    version: 0.1.16
  - apiVersion: v1
    created: 2019-03-27T18:47:22Z
    description: A Helm chart for Kubernetes
    digest: 98535751108445574d9e7055762cf2673ba597e199f94e6f85dc068822d29773
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving-helm/releases/download/0.1.17/serving-0.1.17.tgz
    version: 0.1.17
  - apiVersion: v1
    created: 2019-04-04T14:23:40Z
    description: A Helm chart for Kubernetes
    digest: 9a0229379abf5ce94738d43ee38be01bc96ace80e4b86500066ce3bdecde4c7d
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving-helm/releases/download/2.0.0/serving-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v1
    created: 2019-04-04T14:40:14Z
    description: A Helm chart for Kubernetes
    digest: 6c2f15a41c48c1f4c596d0e60a0bcfa5d4842551c4b21c2fdf139fd8fbb9eae4
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.0.0/serving-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v1
    created: 2019-04-04T15:38:41Z
    description: A Helm chart for Kubernetes
    digest: 193380137249e80f6681831d37c79a75ee1a03363bed1d3fec1715b3fe071a16
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.0.0/serving-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v1
    created: 2019-04-09T16:38:24Z
    description: A Helm chart for Kubernetes
    digest: 188961faa960a15ee9c4f310e5429f90d2f03842a9b062f709bccff638ad84b5
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.0.1/helm.serving-2.0.1.tgz
    version: 2.0.1
  - apiVersion: v1
    created: 2019-04-18T16:05:09Z
    description: A Helm chart for Kubernetes
    digest: 64ab4ec85b396268d91b287d0eaccf936431c8bdac3bea5bdf887dd77d6a7659
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.0.2/helm.serving-2.0.2.tgz
    version: 2.0.2
  - apiVersion: v1
    created: 2019-04-19T09:06:05Z
    description: A Helm chart for Kubernetes
    digest: d643dcb23cf18a4b60a608a29b3a617da42d96ed04406cda229c1454e2fa67b7
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.0.3/helm.serving-2.0.3.tgz
    version: 2.0.3
  - apiVersion: v1
    created: 2019-04-19T12:23:40Z
    description: A Helm chart for Kubernetes
    digest: 1620e299d50bc9a3b4bbbd82eae9d53bd91f959ece28db7979f377db1f08c973
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.0.4/helm.serving-2.0.4.tgz
    version: 2.0.4
  - apiVersion: v1
    created: 2019-11-20T14:48:56Z
    description: A Helm chart for Kubernetes
    digest: 6d037585dab119013ddecfc6cb9c7425ccfed949ed67bf4d32c07912635d2b9c
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.1.0/helm.serving-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v1
    created: 2020-03-26T16:55:21Z
    description: A Helm chart for Kubernetes
    digest: 3f51a004c232bdd0b4a4ab3addc9442d33961b4b33bf1ac9d46874ec351e86b3
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.2.0/helm.serving-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v1
    created: 2020-04-02T09:14:32Z
    description: A Helm chart for Kubernetes
    digest: 7d10ab7f4480861b659776a9605665e02b896afc87c3b713e90b6a77988b52ba
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.2.1/helm.serving-2.2.1.tgz
    version: 2.2.1
  - apiVersion: v1
    created: 2020-06-11T07:27:13Z
    description: A Helm chart for Kubernetes
    digest: 8c025685649ca5eb760d93cf504adf9c9e72513566505d38441314f58138d11b
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.3.0/helm.serving-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v1
    created: 2020-06-30T11:43:41Z
    description: A Helm chart for Kubernetes
    digest: 90462132cce9a32ee83c67c00aca0be31147b3278f791fe3328d48eb5a430f9f
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.3.1/helm.serving-2.3.1.tgz
    version: 2.3.1
  - apiVersion: v1
    created: 2020-07-01T12:46:55Z
    description: A Helm chart for Kubernetes
    digest: 34047d7bf007e3c6fad318993a00fabe635712ccd01982e88300400c7e0b6b63
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.3.1/helm.serving-2.3.1.tgz
    version: 2.3.1
  - apiVersion: v1
    created: 2020-10-14T09:41:59Z
    description: A Helm chart for Kubernetes
    digest: cf2ea1911da0583b3ffea37d0d3df347f38d8fc8b0289b4a4f12b3787cb79043
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.4.0/helm.serving-2.4.0.tgz
    version: 2.4.0
  - apiVersion: v1
    created: 2020-10-30T12:26:38Z
    description: A Helm chart for Kubernetes
    digest: 990bb4b435d381f7d3ce69e43c549f49e4a6ed3aa9255c193d3f393fc9a4d138
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.4.1/helm.serving-2.4.1.tgz
    version: 2.4.1
  - apiVersion: v1
    created: 2020-10-30T14:16:22Z
    description: A Helm chart for Kubernetes
    digest: c31db5b1cf47358bad94d81605d29bc95d8c0876f794dadf32dd98f1bc7e93f0
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.4.2/helm.serving-2.4.2.tgz
    version: 2.4.2
  - apiVersion: v1
    created: 2020-11-05T17:24:14Z
    description: A Helm chart for Kubernetes
    digest: 0f5a28ce341cec1929f1d348c67f8608e35a213e61c77acc0a961780a6d522f8
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/2.4.3/helm.serving-2.4.3.tgz
    version: 2.4.3
  - apiVersion: v1
    created: 2021-06-30T03:57:00Z
    description: A Helm chart for Kubernetes
    digest: 
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/4.4.1/helm.serving-4.4.1.tgz
    version: 4.4.1
  - apiVersion: v1
    created: 2021-06-30T04:04:04Z
    description: A Helm chart for Kubernetes
    digest: ba3a47c9e1704ccd8df12c8e940f8b62b71b07a7e68e427caa1861fecac359e8
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/4.4.2/helm.serving-4.4.2.tgz
    version: 4.4.2
  - apiVersion: v1
    created: 2021-06-30T05:20:42Z
    description: A Helm chart for Kubernetes
    digest: 57460c594414ed62e82c976c6c60b80462b239471ffdbea24067e5303be3eb20
    name: serving
    urls:
    - https://github.com/Hydrospheredata/hydro-serving/releases/download/4.4.3/helm.serving-4.4.3.tgz
    version: 4.4.3
